### PR TITLE
merging the newyorktimes branch with the master

### PR DESCRIPTION
**Pull request by AsmaaShAli**
A request for merging our branch to the master, it's a mockup version of a newyork times article page.
it contains a navbar, the whole article, editors picks on the side and the same footer with all elements.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
This PR is under Review by: **_[TSE] Temitayo Adeleke_**

**Comment by lekegitrepo** [comment]
## Hi @AsmaaShAli and @Phylis05 👏 👏 👏 👏 👏
### _This is really excellent work!!!_
**_You just have few requirements left to fix._**
### Required:
1. The NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

2. The section 'More in Space and Astronomy' should contain links to other articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) the images are missing.

**_This is your version:_**

image

**_This is the original version:_**

image


3. The footer should stick to the bottom part of the screen ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) like the original page image below:


Screenshot (0)


Screenshot (02)

### _Optional:_
* [ ] Add 'px' to the value of the style rule in line 72 and 175 of the style.css file.

If you have any doubt or question contact me on slack.

**Reviewed by: _Temitayo Adeleke_**

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Required changes

**Comment by AsmaaShAli** [comment]
> 
> ## Hi @AsmaaShAli and @Phylis05 clap clap clap clap clap
> ### _This is really excellent work!!!_
> 
> **_You just have few requirements left to fix._**
> ### Required:
> 
>     1. The NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
> 
>     2. The section 'More in Space and Astronomy' should contain links to other articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) the images are missing.
> 
> 
> **_This is your version:_**
> 
> image
> 
> **_This is the original version:_**
> 
> image
> 
>     1. The footer should stick to the bottom part of the screen ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) like the original page image below:
> 
> 
> Screenshot (0)
> 
> Screenshot (02)
> ### _Optional:_
> 
>     * [ ]  Add 'px' to the value of the style rule in line 72 and 175 of the style.css file.
> 
> 
> If you have any doubt or question contact me on slack.
> 
> **Reviewed by: _Temitayo Adeleke_**
> 
>     * Github: [@lekegitrepo](https://github.com/lekegitrepo)
> 
>     * Twitter: [@leketemi](https://twitter.com/leketemi)
> 
>     * Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

We did all the required changes, please check the new live demo.

**Comment by SofiBretz** [comment]
Code under review by SofiBretz. Thanks!✨

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] On the section 'More in Space and Astronomy' consider placing the titles and the size of the images as the original page:

Screenshot from 2020-02-28 08-33-38

Screenshot from 2020-02-28 08-42-25

- [ ] Consider placing the images with a space between the text, the images are overlapping with the text:

Screenshot from 2020-02-28 08-36-02

Screenshot from 2020-02-28 08-36-11

[OPTIONAL]

- [ ] Consider adding a screenshot of your project and the demo link in your readme file.

- [ ] Pull Request has a meaningful title and a short description, [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/
) you can learn about it. 

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by AsmaaShAli** [comment]
> 
> ### Changes required recycle
> ### Hello team star2
> 
> Great work on this project, but you need to fix the issues below before moving on arrow_down
> 
>     * [ ]  On the section 'More in Space and Astronomy' consider placing the titles and the size of the images as the original page:
> 
> 
> Screenshot from 2020-02-28 08-33-38
> 
> Screenshot from 2020-02-28 08-42-25
> 
>     * [ ]  Consider placing the images with a space between the text, the images are overlapping with the text:
> 
> 
> Screenshot from 2020-02-28 08-36-02
> 
> Screenshot from 2020-02-28 08-36-11
> 
> [OPTIONAL]
> 
>     * [ ]  Consider adding a screenshot of your project and the demo link in your readme file.
> 
>     * [ ]  Pull Request has a meaningful title and a short description, [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) you can learn about it.
> 
> 
> _**After making the required changes please submit a new code review request**_
> Good luck! four_leaf_clover You are almost there! muscle
> 
> SofiBretz.

Hi sofi,
I can't take a screenshot of the project, the page is very long, but there's a live demo already in the readme file
also I ran the project on my local machine, my partners machine and the live demo shows the content to be well adjusted. your screenshots is not similar to mine's or my partner's. !!

check these photos : 




I also used FF and Chrome to view them, what browser are you using ?

**Comment by uryelah** [comment]
Hello  **Asmaa Shaaban Ali** & **Phylis Chepchumba**, I'm Sarah, your reviewer for this PR .

I took a look at your live version and the images and text positioning and spacing look good in my browser(Firefox). You did a good job completing the required changes from the last review, congrats! 🥇 

**Great job at:**
- using semantic HTML
- adding the live version link to the README
- communicating really well with the code reviewers

### Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

-------

**Optional changes**

### The bellow was not noticed before so it's marked as optional

- [x]  [OPTIONAL] Your icons are overlapping the navbar when scrolling through the site. Make sure to set the navbar `z-index` above the icons.

Screenshot_2020-02-28 Newyork Times page

-------

**Keep being awesome devs and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by AsmaaShAli** [comment]
> 
> 
> Hello Asmaa Shaaban Ali & Phylis Chepchumba, I'm Sarah, your reviewer for this PR .
> 
> I took a look at your live version and the images and text positioning and spacing look good in my browser(Firefox). You did a good job completing the required changes from the last review, congrats! 1st_place_medal
> 
> **Great job at:**
> 
>     * using semantic HTML
> 
>     * adding the live version link to the README
> 
>     * communicating really well with the code reviewers
> 
> 
> ### Your project is approved! confetti_ball goal_net yellow_heart
> 
> **You may close this Pull Request and merge the changes**
> 
> **Optional changes**
> ### The bellow was not noticed before so it's marked as optional
> 
>     * [x]   [OPTIONAL] Your icons are overlapping the navbar when scrolling through the site. Make sure to set the navbar `z-index` above the icons.
> 
> 
> **Keep being awesome devs and good luck with your next project!**
> 
> Cheers and Happy coding!clapclapclap
> 
> Code review by **Sarah Uryelah Silva Chamorro**
> 
> (Feel free to contact me on slack by the handle of **sarah** if you have any additional question)

Nice tip Sarah, I fixed the navbar 
and thanks for your kind words :-*

**Pull request merged**
